import React from "react";
import { Bar } from "react-chartjs-2";
import "./doublearealine.css"; // Assuming this is your CSS file

import {
  Chart as ChartJS,
  BarElement,
  CategoryScale,
  LinearScale,
  Tooltip,
  Legend,
} from "chart.js";

// Register Chart.js components
ChartJS.register(BarElement, CategoryScale, LinearScale, Tooltip, Legend);

const BarChart = ({ titleData, labels, status, chartData }) => {
  // Default dataset structure
  const data = {
    labels: labels, // Dynamic labels passed as prop
    datasets: [
      {
        label: titleData || "Balance", // Use dynamic titleData or fallback to "Balance"
        data: chartData, // Data passed as prop
        backgroundColor: (context) => {
          const value = context.raw;
          // Color bars based on value
          return value < 0 ? "#fb7d5b" : "#00273a";
        },
        borderColor: "rgba(0, 0, 0, 0.1)",
        borderWidth: 1,
      },
    ],
  };

  const options = {
    responsive: true,
    plugins: {
      legend: {
        display: false, // Disable the legend generated by Chart.js
      },
      tooltip: {
        mode: "index",
        intersect: false,
      },
    },
    scales: {
      x: {
        title: {
          display: true,
          text: "Users", // X-axis title
        },
        grid: {
          display: false, // Remove grid from x-axis
        },
      },
      y: {
        title: {
          display: true,
          text: "Count", // Y-axis title
        },
        beginAtZero: true,
        grid: {
          drawOnChartArea: true, // Draw grid lines on the chart area
          borderColor: "#ccc", // Light grey border color
          borderWidth: 1,
          lineWidth: 1, // Ensure horizontal lines are visible
          color: "#e0e0e0", // Light grey color for horizontal lines
        },
      },
    },
  };

  return (
    <div>
      {/* Flexbox layout for the header */}
      <div className="bar-header-container">
        <h2 className="barchart-heading">
          {titleData}
        </h2>
        <div className="status-container">
          <div className="column">
            <p>{status.p1}</p>
            <p>{status.p2}</p>
            <p>{status.p3}</p>
          </div>
          <div className="column">
          <p>{status.p4}</p>
          <p>{status.p5}</p>
          </div>
        </div>
      </div>
      <div className="graph-chart-container02">
        <Bar data={data} options={options} height={500} width={800} />{" "}
        {/* Increased height */}
      </div>
    </div>
  );
};

export default BarChart;
